apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: minioinstances.miniocontroller.minio.io
spec:
  group: miniocontroller.minio.io
  version: v1beta1
  names:
    kind: MinioInstance
    plural: minioinstances
  scope: Namespaced
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: minio-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: minio-operator
    spec:
      containers:
      - name: minio-operator
        image: nitishtiwari/operator:latest
