apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: minioinstances.minioinstances.minio.io
spec:
  group: minioinstances.minio.io
  version: v1beta1
  names:
    kind: MinioInstance
    plural: minioinstances
  scope: Namespaced
