apiVersion: miniocontroller.minio.io/v1beta1
kind: MinioInstance
metadata:
  name: minio
spec:
  version: RELEASE.2018-08-02T23-11-36Z
  replicas: 4
  credsSecret:
    name: minio-creds-secret # Create the secret using the file ./minio-creds-secret.yaml
  volumeClaimTemplate:
    metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
